### ISSUE TITLE
Consider using few lines of code instead?

### ISSUE THREAD

**Issue by tunnckoCore** [SamVerschueren/rfpify#2]
Hi.  I was just around promises today and seen https://github.com/sindresorhus/pify/issues/31, then looked at `rfpify`. So I started thinking how can we simplify the things and have full compat with pify. And in same time to be minimal.

After few die-hard tries :D finally got the solution. Solution which is logical - gets function which has result-first callback, and returns function that has error-first callback. So then we just can pass that function directly to pify.

So if you consider using `to-callback` (the name is.. nah, but `result-first-to-callback` is too long for me), the rfpify can be something like that

```js
var pify = require('pify')
module.exports = (fn, opts) => pify(toCallback(fn), opts)
```
**note:** it cant be like that cuz should hande the case if `to-callback` throws.

So, that's by me. Check it out at https://github.com/tunnckoCore/to-callback - with 100% coverage and full "greenline" (coverage, build, code climate, tests, docs, notes) and semantic versioning.

I'm open for suggestions and edits. Maybe instead of throwing returning rejected promise?
The cool thing is that it is pretty small and can be integrated directly on `pify` if Sindre want.

Charlike,
cheers.

**Comment by SamVerschueren** [comment]
Hi @tunnckoCore. Sorry for the late reply, I forgot about this. It was indeed on my todo list to reduce the common code between `pify` and `rfpify`. Since the latest version, `pify` now supports non error-first callbacks. For that reason, I deprecated this package in favour of `pify` because there is no need to support this any longer. Thanks for looking into this and for the extensive explanation.
